apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: springtrader
    docker:
      cacheFrom:
        - docker.artifactory.liatr.io/liatrio/springtrader-builder:latest
        - docker.artifactory.liatr.io/liatrio/springtrader-runner:latest
  - image: sqlfdb 
    context: ./sqlfdb
  local: {}

deploy:
  helm:
    releases:
      - name: springtrader 
        chartPath: ./charts/springtrader
        values:
          image: springtrader 
          sqlfdb: sqlfdb 
