### [build] 
apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: springtrader
    docker:
      target: runner
      cacheFrom:
        - 489130170427.dkr.ecr.us-east-1.amazonaws.com/springtrader-builder:latest
        - 489130170427.dkr.ecr.us-east-1.amazonaws.com/springtrader-runner:latest
  - image: sqlfdb
    docker:
      target: sqlfdb
      cacheFrom:
        - 489130170427.dkr.ecr.us-east-1.amazonaws.com/springtrader-builder:latest
        - 489130170427.dkr.ecr.us-east-1.amazonaws.com/springtrader-runner:latest
  local: {}
### [build] 

### [deploy] 
deploy:
  helm:
    releases:
      - name: springtrader 
        chartPath: ./charts/springtrader
        wait: true
        values:
          image: springtrader 
          sqlfdb: sqlfdb 
        setValueTemplates:
          istioDomain: "{{.ISTIO_DOMAIN}}"
          productName: "{{.PRODUCT_NAME}}"
profiles:
- name: kind
  activation:
  - kubeContext: kind-kind
  patches:
  - op: add
    path: /deploy/helm/releases/0/setValues
    value: 
      storageClassName: standard
### [deploy] 
