apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: springtrader
    context: .
    docker:
      target: runner
      buildArgs:
        target: runner
        tag: docker.artifactory.liatr.io/liatrio/springtrader:latest
        cache-from: gradle-builder,docker.artifactory.liatr.io/liatrio/springtrader
  - image: sqlfdb 
    context: ./sqlfdb
  local: {}

deploy:
  helm:
    releases:
      - name: springtrader 
        chartPath: ./charts/springtrader
        values:
          image: docker.artifactory.liatr.io/liatrio/springtrader 
          sqlfdb: sqlfdb 
