apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: gradle-builder
    context: .
    docker:
      target: builder
  - image: docker.artifactory.liatr.io/liatrio/springtrader
    context: .
    docker:
      cacheFrom:
        - gradle-builder
        - docker.artifactory.liatr.io/liatrio/springtrader
  - image: sqlfdb 
    context: ./sqlfdb

  local: {}

deploy:
  helm:
    releases:
      - name: springtrader 
        chartPath: ./charts/springtrader
        values:
          image: docker.artifactory.liatr.io/liatrio/springtrader 
          sqlfdb: sqlfdb 
