apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: springtrader-builder
    docker:
      target: builder
  - image: springtrader-runner
    docker:
      target: runner
  tagPolicy:
    envTemplate:
      template: "{{ .IMAGE_NAME }}:latest"
