apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: springtrader-cache-refresh
  namespace: toolchain
  labels:
    k8s-app: springtrader-cache-refresh
spec:
  selector:
    matchLabels:
      name: springtrader-cache-refresh
  template:
    metadata:
      labels:
        name: springtrader-cache-refresh
    spec:
      containers:
      - name: springtrader-cache-refresh
        image: 489130170427.dkr.ecr.us-east-1.amazonaws.com/builder-image-skaffold:v2.0.2-28-g0fadddc
        command: ["/bin/sh"]
        args: ["-c", "while true; do docker pull $CACHE_IMAGE_REPO/springtrader-builder:latest; docker pull $CACHE_IMAGE_REPO/springtrader-runner:latest; sleep 600; done"]
        env:
        - name: CACHE_IMAGE_REPO
          value: "harbor.toolchain.lead.prod.liatr.io/liatrio"
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker
        resources:
          requests:
            cpu: 10m
            memory: 15Mi
          limits:
            cpu: 200m
            memory: 50Mi
      volumes:
      - hostPath:
          path: /var/run/docker.sock
          type: ""
        name: docker

