apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: springtrader-builder
    context: ./test
    docker:
      target: builder
      noCache: true
  - image: springtrader-runner
    context: ./test
    docker:
      target: runner
  tagPolicy:
    envTemplate:
      template: "{{ .IMAGE_NAME }}:latest"
