name: push
on: 
- push
- pull_request

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - id: gitextra
      uses: liatrio/github-actions/git-extra@master
    - uses: azure/docker-login@v1
      with:
        login-server: harbor.toolchain.lead.prod.liatr.io/liatrio
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    - id: skaffold
      uses: liatrio/github-actions/skaffold-build@master
      with:
        default_repo: harbor.toolchain.lead.prod.liatr.io/liatrio
        skaffold_file_path: ./.cache/skaffold.yaml
